name: Daily Update

on:
  workflow_dispatch:
  # schedule:
    # - cron: "0 4 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Run daily update script
        env:
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          KEY: ${{ secrets.KEY }}
          POS: ${{ secrets.POS }}
        run: |
          npm install
          npm start
